development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: practical_dev
  username: postgres
  password: postgres
  host: localhost
  # url: postgres://chris:root@18.132.163.19:5432/testdb

test: &test
  adapter: postgresql
  encoding: unicode
  pool: 5t
  database: practical_test
  username: postgres
  password: postgres
  host: localhost

staging:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  database: practical_staging
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  database: practical_prod
  host: localhost
